/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as PublicRouteImport } from './../routes/_public'
import { Route as ProtectedRouteImport } from './../routes/_protected'
import { Route as PublicIndexRouteImport } from './../routes/_public/index'
import { Route as ProtectedVocabularyRouteImport } from './../routes/_protected/vocabulary'
import { Route as ProtectedReviewHistoryRouteImport } from './../routes/_protected/review-history'
import { Route as ProtectedReviewRouteImport } from './../routes/_protected/review'
import { Route as ProtectedQuizRouteImport } from './../routes/_protected/quiz'
import { Route as ProtectedAccessTokenRouteImport } from './../routes/_protected/access-token'
import { Route as PublicSearchWordRouteImport } from './../routes/_public/search/$word'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedVocabularyRoute = ProtectedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReviewHistoryRoute = ProtectedReviewHistoryRouteImport.update({
  id: '/review-history',
  path: '/review-history',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReviewRoute = ProtectedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQuizRoute = ProtectedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccessTokenRoute = ProtectedAccessTokenRouteImport.update({
  id: '/access-token',
  path: '/access-token',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicSearchWordRoute = PublicSearchWordRouteImport.update({
  id: '/search/$word',
  path: '/search/$word',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/access-token': typeof ProtectedAccessTokenRoute
  '/quiz': typeof ProtectedQuizRoute
  '/review': typeof ProtectedReviewRoute
  '/review-history': typeof ProtectedReviewHistoryRoute
  '/vocabulary': typeof ProtectedVocabularyRoute
  '/search/$word': typeof PublicSearchWordRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/access-token': typeof ProtectedAccessTokenRoute
  '/quiz': typeof ProtectedQuizRoute
  '/review': typeof ProtectedReviewRoute
  '/review-history': typeof ProtectedReviewHistoryRoute
  '/vocabulary': typeof ProtectedVocabularyRoute
  '/search/$word': typeof PublicSearchWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/access-token': typeof ProtectedAccessTokenRoute
  '/_protected/quiz': typeof ProtectedQuizRoute
  '/_protected/review': typeof ProtectedReviewRoute
  '/_protected/review-history': typeof ProtectedReviewHistoryRoute
  '/_protected/vocabulary': typeof ProtectedVocabularyRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/search/$word': typeof PublicSearchWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access-token'
    | '/quiz'
    | '/review'
    | '/review-history'
    | '/vocabulary'
    | '/search/$word'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/access-token'
    | '/quiz'
    | '/review'
    | '/review-history'
    | '/vocabulary'
    | '/search/$word'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/login'
    | '/_protected/access-token'
    | '/_protected/quiz'
    | '/_protected/review'
    | '/_protected/review-history'
    | '/_protected/vocabulary'
    | '/_public/'
    | '/_public/search/$word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/vocabulary': {
      id: '/_protected/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof ProtectedVocabularyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/review-history': {
      id: '/_protected/review-history'
      path: '/review-history'
      fullPath: '/review-history'
      preLoaderRoute: typeof ProtectedReviewHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/review': {
      id: '/_protected/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ProtectedReviewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/quiz': {
      id: '/_protected/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof ProtectedQuizRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/access-token': {
      id: '/_protected/access-token'
      path: '/access-token'
      fullPath: '/access-token'
      preLoaderRoute: typeof ProtectedAccessTokenRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/search/$word': {
      id: '/_public/search/$word'
      path: '/search/$word'
      fullPath: '/search/$word'
      preLoaderRoute: typeof PublicSearchWordRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAccessTokenRoute: typeof ProtectedAccessTokenRoute
  ProtectedQuizRoute: typeof ProtectedQuizRoute
  ProtectedReviewRoute: typeof ProtectedReviewRoute
  ProtectedReviewHistoryRoute: typeof ProtectedReviewHistoryRoute
  ProtectedVocabularyRoute: typeof ProtectedVocabularyRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccessTokenRoute: ProtectedAccessTokenRoute,
  ProtectedQuizRoute: ProtectedQuizRoute,
  ProtectedReviewRoute: ProtectedReviewRoute,
  ProtectedReviewHistoryRoute: ProtectedReviewHistoryRoute,
  ProtectedVocabularyRoute: ProtectedVocabularyRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicSearchWordRoute: typeof PublicSearchWordRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicSearchWordRoute: PublicSearchWordRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
