/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as ReviewHistoryRouteImport } from './routes/review-history'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchWordRouteImport } from './routes/search.$word'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewHistoryRoute = ReviewHistoryRouteImport.update({
  id: '/review-history',
  path: '/review-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchWordRoute = SearchWordRouteImport.update({
  id: '/search/$word',
  path: '/search/$word',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/review': typeof ReviewRoute
  '/review-history': typeof ReviewHistoryRoute
  '/vocabulary': typeof VocabularyRoute
  '/search/$word': typeof SearchWordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/review': typeof ReviewRoute
  '/review-history': typeof ReviewHistoryRoute
  '/vocabulary': typeof VocabularyRoute
  '/search/$word': typeof SearchWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/review': typeof ReviewRoute
  '/review-history': typeof ReviewHistoryRoute
  '/vocabulary': typeof VocabularyRoute
  '/search/$word': typeof SearchWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/quiz'
    | '/review'
    | '/review-history'
    | '/vocabulary'
    | '/search/$word'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/quiz'
    | '/review'
    | '/review-history'
    | '/vocabulary'
    | '/search/$word'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/quiz'
    | '/review'
    | '/review-history'
    | '/vocabulary'
    | '/search/$word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRoute
  ReviewRoute: typeof ReviewRoute
  ReviewHistoryRoute: typeof ReviewHistoryRoute
  VocabularyRoute: typeof VocabularyRoute
  SearchWordRoute: typeof SearchWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-history': {
      id: '/review-history'
      path: '/review-history'
      fullPath: '/review-history'
      preLoaderRoute: typeof ReviewHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$word': {
      id: '/search/$word'
      path: '/search/$word'
      fullPath: '/search/$word'
      preLoaderRoute: typeof SearchWordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRoute,
  ReviewRoute: ReviewRoute,
  ReviewHistoryRoute: ReviewHistoryRoute,
  VocabularyRoute: VocabularyRoute,
  SearchWordRoute: SearchWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
